name: SystemiseMe
favicon: null
layout_spectrum: 0.35030791186727583
typography_spectrum: 0.10034813941456378
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.643328047124669
  lightness: 0.5204291702248156
  saturation: 0.7456901296973228
  rhythmicContrast: 0.9879463647957891
purpose: []
